id: I51353DE3
legacy_id: P006757
ocr_import_info:
  bdrc_scan_id: W27300
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T12:28:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:58:25.757092+00:00'
last_modified: 2022-09-02 15:06:38.317605
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27300
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27300
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་གླིང་པ། （སྡེ་དགེ་པར་མ།）
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6133396333549177
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I4439:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4439
      total_pages: 918
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4439.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6498187907431011
    legacy_id: v004
  I4437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4437
      total_pages: 882
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4437.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6329678553517127
    legacy_id: v002
  I4444:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4444
      total_pages: 720
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4444.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6263489069489231
    legacy_id: v009
  I4443:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4443
      total_pages: 816
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4443.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6580976242704891
    legacy_id: v008
  I4440:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4440
      total_pages: 892
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4440.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5760986428255183
    legacy_id: v005
  I4436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4436
      total_pages: 1026
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4436.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6358154242638895
    legacy_id: v001
  I4438:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4438
      total_pages: 878
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4438.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5863191526141414
    legacy_id: v003
  I4442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4442
      total_pages: 862
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4442.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5577454914117016
    legacy_id: v007
  I4441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4441
      total_pages: 606
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4441.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5830693839092528
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
