id: I51353DE3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T12:34:14+00:00'
last_modified: '2022-06-08T06:38:41.586798+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27300
  title: གསུང་འབུམ། འཇིགས་མེད་གླིང་པ། （སྡེ་དགེ་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9C31:
      image_group_id: I4436
      title: ''
      total_pages: 1026
      order: 1
      base_file: 9C31.txt
    F370:
      image_group_id: I4437
      title: ''
      total_pages: 882
      order: 2
      base_file: F370.txt
    '7276':
      image_group_id: I4438
      title: ''
      total_pages: 878
      order: 3
      base_file: 7276.txt
    '9387':
      image_group_id: I4439
      title: ''
      total_pages: 918
      order: 4
      base_file: 9387.txt
    B69B:
      image_group_id: I4440
      title: ''
      total_pages: 892
      order: 5
      base_file: B69B.txt
    C99D:
      image_group_id: I4441
      title: ''
      total_pages: 606
      order: 6
      base_file: C99D.txt
    FC10:
      image_group_id: I4442
      title: ''
      total_pages: 862
      order: 7
      base_file: FC10.txt
    F66D:
      image_group_id: I4443
      title: ''
      total_pages: 816
      order: 8
      base_file: F66D.txt
    B6C0:
      image_group_id: I4444
      title: ''
      total_pages: 720
      order: 9
      base_file: B6C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
